version: "3"

services:
  php:
    build: ./php/
    container_name: contphp
    hostname: host-php
    volumes:
      - ./apps/lumen:/appdata/www/lumen
    networks:
      - net-lacia

  web:
    build: ./nginx/
    container_name: contweb
    hostname: contweb
    ports:
      # lumen-api
      - "9080:80"
      # movies/data.json
      - "9090:90"
      # vue
      - "9100:100"
    volumes:
      # movies/data.json
      - ./apps/movies:/appdata/www/movies
      - ./apps/vue:/appdata/www/vue
      - ./nginx/site.conf:/etc/nginx/conf.d/default.conf
    networks:
      - net-lacia

networks:
  net-lacia:
    driver: bridge